### ISSUE TITLE
SSL verify error, when sending to coveralls.io

### ISSUE THREAD

**Issue by metawilm** [fukamachi/cl-coveralls#10]
After the coverage is calculated, the transfer of that data to coveralls.io fails with:
`SSL verify error: 20 X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY`
https://travis-ci.org/metawilm/cl-custom-hash-table/builds/205015355

Do you have an idea what the cause is, or how to work around it?
(Thanks for creating this library!)

**Comment by fukamachi** [comment]
This is because of Dexador, HTTP client this library depends on.
Several days ago, Dexador bundles common SSL certificates, so such verification error has been fixed with the latest version.

Until the next Quicklisp update, doing git clone Dexador from GitHub at 'install' in .travis.yml would work.

**Comment by metawilm** [comment]
Thanks, that resolved it.
